### ISSUE TITLE
The maxEventBufferCapacity property in databridge configs

### ISSUE THREAD

**Issue by Methma** [wso2/streaming-integrator#230]
**Description:**
The comment for the 'maxEventBufferCapacity' property in the deployment.yaml file should be changed as follows as the current 'internally in MB' is misleading.

```
databridge.config:

  workerThreads: 10
    # The maximum size allowed for the event receiving buffer in bytes
    # THIS IS A MANDATORY FIELD
  maxEventBufferCapacity: 10000000
```

**Affected Product Version:**
SP-4.2.0
SP-4.3.0
SP-4.4.0
SI-1.0.0
SI-1.1.0
SI-tooling-1.0.0
SI-tooling-1.1.0
